# Copyright (c) 2021-2025, NVIDIA CORPORATION & AFFILIATES
#
# SPDX-License-Identifier: BSD-3-Clause


[build-system]
requires = ["Cython>=0.29.22", "packaging", "setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"
